# Generated by Django 6.0.4 on 2026-04-23 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Manager", "Manager"),
                            ("Developer", "Developer"),
                            ("Analyst", "Analyst"),
                            ("HR", "HR"),
                            ("Sales", "Sales"),
                            ("Support", "Support"),
                            ("tester", "tester"),
                        ],
                        max_length=50,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
